Dagger2
sntgl/AvitoTrainee pull request #1
Opened 2022-01-29 13:46 UTC by sntgl

Применил DI на основе Dagger2.
Остался вопрос с аннотациями для разрешения зависимостей между компонентами.
Также есть вопрос по скоупам, насколько их резонно использую, где стоит отказаться, где мб добавить.

2022-01-31 11:01 UTC, phansier requested changes

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/city/data/CityRepository.kt
> +    ): Flow<List<CityModel>?>
тут и в других интерфейсах с Flow
лучше сделать вложенный тип ненулабельным
если с источника данных пришел null -  либо не эмитить его совсем во флоу, либо вместо него эмитить ошибку

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/city/di/CityModule.kt
> +class CityModule
а зачем тебе лишний интерфейс тут? можно сделать CityModule интерфейсом и перенести bind в него

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/city/ui/viewmodel/CityViewModel.kt
> +    private val db = database.cityDao()
лучше, наверное, назвать dao переменную

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/forecast/di/ForecastModule.kt
> +class ForecastModule
тоже лишний класс

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/forecast/di/ForecastComponent.kt
> +    interface Builder {
Component.Builder → Component-Factory
посмотри  "Рекомендации по Dagger" в доке

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/forecast/di/ForecastComponent.kt
> +@kotlin.annotation.Retention(AnnotationRetention.RUNTIME)
можно заимпортить

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/MainActivity.kt
> +                        val component = DaggerForecastComponent.builder().deps(appComponent).build()
не уверен, что component нужно создавать внутри Compose

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/di/AppComponent.kt
> +    @ExperimentalAnimationApi
чтобы не тащить Experimental аннотации по всему проекту имхо лучше использовать `@OptIn`

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/di/AppModule.kt
> +            .addQueryApiKey("appid", Key.WEATHER_API_KEY)
можно использовать один OkHttp в двух ретрофитах, но apikey подставлять в параметрах запроса или при конфигурации ретрофита?

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/di/AppModule.kt
> +            .addQueryApiKey("appid", Key.WEATHER_API_KEY)
а, кажется нельзя

2022-01-31 11:01 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/di/AppModule.kt
> +    fun provideForecastRetrofit(
forecast и weather части можно наверное по отдельным компонентам разнести?

2022-01-31 13:06 UTC, sntgl commented on app/src/main/java/ru/tagilov/avitotrainee/forecast/di/ForecastModule.kt
> +class ForecastModule
оставил для однообразия

2022-02-01 12:57 UTC, sntgl commented
@phansier

2022-02-01 15:50 UTC, phansier approved these changes

2022-02-01 15:50 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/core/util/TypedResult.kt
> +    data class Ok<T>(@Transient val result: T) : TypedResult<T>()
зачем transient?

2022-02-01 15:50 UTC, phansier commented on app/src/main/java/ru/tagilov/avitotrainee/root/di/AppComponent.kt
> +import ru.tagilov.avitotrainee.core.di.AppScope
лишний импорт кажется

2022-02-04 13:35 UTC, merged